# syntax=docker/dockerfile:1.6
# Generated by AEGIS DevOps Agent — DO NOT edit manually
# Linear issue: SYS-266

# ────────────────────────────────────────────────────────────────────────────
# Stage 1 — deps: install production dependencies only
# ────────────────────────────────────────────────────────────────────────────
FROM node:20-slim AS deps
WORKDIR /app
COPY package*.json ./
# Use npm ci when a committed lockfile exists; fall back to npm install so the
# image still builds for generated repos that ship package.json without a lock.
# hadolint ignore=DL3016
RUN --mount=type=cache,target=/root/.npm \
    if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi

# ────────────────────────────────────────────────────────────────────────────
# Stage 2 — build: compile TypeScript / bundle assets
# ────────────────────────────────────────────────────────────────────────────
FROM node:20-slim AS build
WORKDIR /app
COPY package*.json ./
# hadolint ignore=DL3016
RUN --mount=type=cache,target=/root/.npm \
    if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build

# ────────────────────────────────────────────────────────────────────────────
# Stage 3 — runtime: minimal image with only production artefacts
# ────────────────────────────────────────────────────────────────────────────
FROM node:20-slim AS runtime
WORKDIR /app

COPY --from=deps  /app/node_modules ./node_modules
COPY --from=build /app/dist         ./dist
COPY package*.json ./

# OCI image labels (§10.3)
LABEL org.opencontainers.image.revision="HEAD" \
      org.opencontainers.image.source="https://github.com/Nabhan-Systalent/project-default-taskflowapp" \
      aegis.linear-issue="SYS-266"

EXPOSE 3000
USER node
CMD ["node", "dist/main.js"]


